#!/usr/bin/env bash
#
# Assemble the SDK as a tarball -- an A2 toolchain that needs no Docker to use.
#
# What comes out is a directory (and, unless told otherwise, a tarball of it) holding exactly
# what the Docker image holds at /opt/a2sdk, plus the `ob` CLI, the examples, the test suites
# and a self-check. Unpack it anywhere, run ./ob; nothing is installed, nothing is exported,
# no daemon runs. This is the artefact for someone who wants the compiler and the language
# server in their editor and has no interest in containers.
#
# It is deliberately the same layout as the AArch64 bundle (tests/a64-bundle.sh) and the same
# layout as the image, because `ob` finds its SDK beside itself and reads the target
# architecture off the runtime's own ELF header -- so one script serves all three.
#
# Inputs, all produced by the tree's own toolchain and none of them fetched:
#
#   target/Linux64            `task Linux64` -- the runtime and the x86-64 objects (required)
#   target/Win64              `task Win64`   -- the Win64 objects, for `ob build -t win64`
#   target/A64/bin            `task a64-stdlib` -- the AArch64 objects, for `ob build -t a64`
#
# The two cross targets are optional: without them the bundle is smaller and `ob` says the
# target is unavailable rather than failing in the middle of a link.
#
# Usage: tests/bundle.sh [-o output-dir] [--no-tar] [build directory]

set -eo pipefail

absolute() {
	case "$1" in
		/*) printf '%s\n' "$1" ;;
		*) printf '%s\n' "$PWD/$1" ;;
	esac
}

root="$(cd "$(dirname "$0")/.." && pwd)"
out=""
tar=1
args=()
while [ $# -gt 0 ]; do
	case "$1" in
		-o|--output) out="$2"; shift 2 ;;
		--no-tar) tar=0; shift ;;
		-*) echo "unknown option: $1" >&2; exit 2 ;;
		*) args+=("$1"); shift ;;
	esac
done
build="$(absolute "${args[0]:-$root/target/Linux64}")"

# The tag this tree is at, or what the caller says. The override exists for the image build:
# .git is not in the Docker context, so inside the builder there is nothing to describe.
version="${A2_SDK_VERSION:-$(git -C "$root" describe --tags --always --dirty 2>/dev/null || echo dev)}"
[ -n "$out" ] || out="$root/target/bundle"
out="$(absolute "$out")"
name="minia2-sdk-$version-linux-amd64"

runtime="$build/oberon"
if [ ! -x "$runtime" ]; then
	echo "no runtime in $build; run 'task Linux64' first" >&2
	exit 2
fi
if [ ! -f "$build/bin/Compiler.SymUu" ]; then
	echo "no compiler objects in $build/bin; run 'task Linux64' first" >&2
	exit 2
fi

# A runtime older than the sources it was built from is the kind of stale that does not
# announce itself: it runs, it passes the checks it passed last month, and it is missing
# whatever was fixed since. Said out loud rather than made fatal -- there are honest reasons
# to bundle an older build, and none of them is helped by a script that refuses.
newest="$(find "$root/source" -name '*.Mod' -newer "$runtime" -print -quit 2>/dev/null || true)"
if [ -n "$newest" ]; then
	echo "warning: $build/oberon is older than $(basename "$newest") and probably others;" >&2
	echo "         'task Linux64' first if this bundle is meant to carry the current tree" >&2
fi

rm -rf "$out"
mkdir -p "$out/lib" "$out/lib-sym" "$out/examples" "$out/tests"

# The runtime, its configuration, and the boot module list `ob build` links against.
install -m 755 "$runtime" "$out/oberon"
install -m 644 "$build/oberon.cfg" "$out/oberon.cfg"
install -m 644 "$root/configs/moduleListLinux.txt" "$out/boot-modules.txt"

# lib/ is the headless core: everything whose import closure never reaches the window manager,
# the display or the raster (docker/headless-core.txt, generated by docker/gen-headless-core.sh).
# lib-sym/ is every symbol file there is, and only symbol files: the language server resolves
# imports through it, including the graphical modules it can check but not link.
copied=0
while read -r m; do
	case "$m" in ''|\#*) continue ;; esac
	for e in SymUu GofUu; do
		[ -f "$build/bin/$m.$e" ] && install -m 644 "$build/bin/$m.$e" "$out/lib/" && copied=1
	done
done < "$root/docker/headless-core.txt"
[ "$copied" = 1 ] || { echo "no headless-core objects found in $build/bin" >&2; exit 1; }
install -m 644 "$build"/bin/*.SymUu "$out/lib-sym/"

# The cross targets, each present only if its objects are, and both looked for beside the build
# that was named rather than under target/ -- so a bundle assembled out of a build tree somewhere
# else picks up that tree's Win64 and A64, not the ones in the repository.
targets="$(dirname "$build")"
if ls "$targets/Win64/bin"/*.SymWw >/dev/null 2>&1; then
	mkdir -p "$out/lib-win64"
	install -m 644 "$root/configs/moduleListWin.txt" "$out/boot-modules-win64.txt"
	# The Win64 boot modules (Kernel32, WinFS) are not in the headless core -- that list is the
	# Linux closure -- so the two lists together are what a Windows link needs.
	{ cat "$root/docker/headless-core.txt" "$root/configs/moduleListWin.txt"; } | sort -u |
	while read -r m; do
		case "$m" in ''|\#*) continue ;; esac
		for e in SymWw GofWw; do
			[ -f "$targets/Win64/bin/$m.$e" ] && install -m 644 "$targets/Win64/bin/$m.$e" "$out/lib-win64/"
		done
	done
fi
# No headless-core filter for A64: what is in that directory is what tests/a64-stdlib-check.sh
# compiled from the list, and there is no second build of it to choose from.
if ls "$targets/A64/bin"/*.SymU8 >/dev/null 2>&1; then
	mkdir -p "$out/lib-a64"
	install -m 644 "$targets/A64/bin"/*.SymU8 "$targets/A64/bin"/*.GofU8 "$out/lib-a64/"
fi

# The CLI, the license A2 is redistributed under, the std package manifests `ob lint` and
# `ob get` read, something to compile on the first minute, and the suites that answer for the
# release. The suites ship because a tarball nobody can check is a tarball nobody should trust.
install -m 755 "$root/docker/ob" "$out/ob"
install -m 755 "$root/tests/bundle-selfcheck.sh" "$out/run.sh"
install -m 644 "$root/license.txt" "$out/LICENSE.txt"
cp -r "$root/packages" "$out/packages"
install -m 644 "$root"/docker/examples/*.Mod "$out/examples/"
install -m 644 "$root"/tests/*.Test "$out/tests/"
install -m 644 "$root/tests/a2test-expected.txt" "$out/tests/"
printf '%s\n' "$version" > "$out/VERSION"

cat > "$out/README" <<'EOF'
A2 / Active Oberon SDK -- the compiler, the standard library and the language server, in one
directory. No Docker, no installer, no daemon, nothing written outside this directory.

Needs: 64-bit x86 Linux with a glibc C library, bash and coreutils. `ob get` additionally
wants git and jq; every other verb works without them.

    ./ob version                      what this SDK is and which targets it has
    ./ob run examples/Hello.Mod       compile and run, in one step
    ./ob build examples/Hello.Mod     a standalone ELF with the runtime baked in
    ./ob repl                         the interactive A2 shell
    ./ob test                         the language suites (thousands of cases)
    ./run.sh                          check this SDK works: every verb, then the suites
    ./run.sh --quick                  the same without the suites

To have `ob` on the PATH without moving anything, link it -- `ob` follows the link back to
this directory and finds its runtime there:

    mkdir -p ~/.local/bin && ln -sf "$PWD/ob" ~/.local/bin/ob

Editors: `ob lsp` speaks LSP over stdio (diagnostics, hover, go-to-definition, completion,
signature help, references, outline, semantic tokens, rename, formatting, code actions).
Point your editor's Active Oberon client at the absolute path of `ob` with the argument `lsp`
-- for Neovim, `cmd = { "/path/to/ob", "lsp" }`.

Cross targets, if this bundle carries their objects (`ob version` says which):

    ./ob build examples/Hello.Mod -t win64 -o hello.exe    a Windows PE64 console .exe
    ./ob build examples/Hello.Mod -t a64 -o hello-arm64    an AArch64 ELF (Pi 4/5, ARM server)

For a machine that is itself AArch64 -- a board, a phone under Termux -- take the AArch64
bundle instead (tests/a64-bundle.sh in the source tree): there a64 is not a cross target but
the native one, and the compiler runs on the device.

Sources, issues and the Docker image: https://github.com/AndriiPuhachenko/minia2
A2 is BSD-3-Clause, ETH Zurich -- see LICENSE.txt.
EOF

echo "bundle: $out ($(du -sh "$out" | cut -f1))"
echo "  version : $version"
echo "  stdlib  : $(ls "$out/lib"/*.SymUu | wc -l) modules (linux64), $(ls "$out/lib-sym"/*.SymUu | wc -l) symbols for the language server"
[ -d "$out/lib-win64" ] && echo "  win64   : $(ls "$out/lib-win64"/*.SymWw | wc -l) modules"
[ -d "$out/lib-a64" ] && echo "  a64     : $(ls "$out/lib-a64"/*.SymU8 | wc -l) modules"

if [ "$tar" = 1 ]; then
	tarball="$(dirname "$out")/$name.tar.gz"
	# --transform so the tarball unpacks into a named directory rather than over the cwd
	tar czf "$tarball" -C "$(dirname "$out")" --transform "s|^$(basename "$out")|$name|" \
		"$(basename "$out")"
	echo "tarball: $tarball ($(du -sh "$tarball" | cut -f1))"
	echo
	echo "to use:  tar xzf $(basename "$tarball") && cd $name && ./run.sh --quick"
fi
