#!/usr/bin/env python3
"""
Write source/Unicode.Mod: the character database as a table, not as a file read at run time.

A2 already had the UCD -- UnicodeProperties.Mod parses data/UnicodeData.txt on demand -- but it
reads it through Texts and Codecs, which reach the window system, so the headless SDK cannot have
it and neither can bare metal. This turns the same file into a compiled table instead.

The shape is runs: over the whole code space the triple (category, upper delta, lower delta) is
constant across long stretches, 2642 of them for 1114112 code points, taking only 151 distinct
values. So the module carries a sorted run table and a small value table, and a lookup is a binary
search. The data travels as hex inside ordinary string literals -- no escaping question, and no
literal longer than a line.

    python3 tests/gen-unicode.py            # write source/Unicode.Mod
    python3 tests/gen-unicode.py --check    # fail if the file on disk is not what this produces
"""
import hashlib, io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UCD = os.path.join(ROOT, "data", "UnicodeData.txt")
OUT = os.path.join(ROOT, "source", "Unicode.Mod")
N = 0x110000
PER_LINE = 12                      # runs per literal: 12 * 8 hex characters = 96

CATEGORIES = ["Cn", "Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No",
              "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So",
              "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co"]

def read():
    cat = [0] * N
    up = [0] * N
    lo = [0] * N
    rows = []
    for line in io.open(UCD, encoding="utf-8"):
        f = line.split(";")
        if len(f) < 15: continue
        rows.append((int(f[0], 16), f[1], f[2],
                     int(f[12], 16) if f[12] else 0, int(f[13], 16) if f[13] else 0))
    index = {c: i for i, c in enumerate(CATEGORIES)}
    i = 0
    while i < len(rows):
        cp, name, c, u, l = rows[i]
        if c not in index: sys.exit("unknown general category %r at %04X" % (c, cp))
        if name.endswith(", First>"):          # a range, closed by the next line
            last = rows[i + 1][0]
            for x in range(cp, last + 1): cat[x] = index[c]
            i += 2
            continue
        cat[cp] = index[c]
        if u: up[cp] = u - cp
        if l: lo[cp] = l - cp
        i += 1
    return cat, up, lo

def build(cat, up, lo):
    values, order, runs = {}, [], []
    prev = None
    for cp in range(N):
        v = (cat[cp], up[cp], lo[cp])
        if v != prev:
            if v not in values:
                values[v] = len(order); order.append(v)
            runs.append((cp, values[v]))
            prev = v
    return runs, order

# One code point added by each release, so the header can say how old the file is instead of
# leaving the reader to guess from a hash. The newest one present names the version.
MARKERS = [("3.2", 0x0220), ("4.0", 0x0221), ("4.1", 0x0237), ("5.0", 0x0242), ("5.1", 0x0370),
           ("5.2", 0x0524), ("6.0", 0x0526), ("6.1", 0x058F), ("7.0", 0x037F), ("8.0", 0x08B3),
           ("9.0", 0x08B6), ("10.0", 0x0860), ("11.0", 0x07FD), ("12.0", 0x0C77), ("13.0", 0x08BE),
           ("14.0", 0x061D), ("15.0", 0x0CF3)]

def version(cat):
    seen = "older than 3.2"
    for name, cp in MARKERS:
        if cat[cp] != 0: seen = name
    return seen

def main():
    cat, up, lo = read()
    runs, values = build(cat, up, lo)
    if len(values) > 0xFF: sys.exit("more than 255 distinct values, the run encoding needs widening")
    digest = hashlib.sha1(io.open(UCD, "rb").read()).hexdigest()

    out = io.StringIO()
    w = out.write
    w('MODULE Unicode;\n')
    w('(**\n')
    w('\tAUTHOR "Andrii Puhachenko";\n')
    w('\tPURPOSE "The Unicode character database as a compiled table: categories and simple case mapping";\n')
    w('\tLIMITATIONS\n')
    w('\t\t"- simple case mapping only: the one-to-many mappings of SpecialCasing.txt (sharp s to SS)\n')
    w('\t\t   and every locale rule are not here;\n')
    w('\t\t - no normalisation, no decomposition, no bidirectional class -- categories and case is\n')
    w('\t\t   what the string layer and the pattern matcher need, and adding the rest is adding\n')
    w('\t\t   columns to the same generator."\n')
    w('*)\n')
    w('(*\tGENERATED by tests/gen-unicode.py -- do not edit.\n')
    w('\tSource: data/UnicodeData.txt, sha1 %s -- Unicode %s.\n' % (digest, version(cat)))
    w('\tA newer table is a newer file in data/ and this script run again; nothing here is hand-made.\n')
    w('\t%d runs over %d code points, %d distinct (category, upper delta, lower delta) values.\n'
      % (len(runs), N, len(values)))
    w('\tThe module UnicodeProperties reads that same file at run time through Texts and Codecs,\n')
    w('\twhich is why it cannot travel in a headless SDK and this table can. *)\n\n')
    w('CONST\n')
    w('\t(** general categories, the two-letter names of the standard *)\n')
    for i, c in enumerate(CATEGORIES):
        w('\t%s* = %d;%s' % (c, i, '\n' if (i % 6 == 5 or i == len(CATEGORIES) - 1) else ''))
    w('\n\tMaxCode* = 10FFFFH;\t(** the largest code point Unicode defines *)\n\n')
    w('\tnofRuns = %d;\n\tnofValues = %d;\n\n' % (len(runs), len(values)))
    w('VAR\n')
    w('\tstart: ARRAY nofRuns OF SIGNED32;\t(* first code point of the run, ascending *)\n')
    w('\tvalue: ARRAY nofRuns OF SIGNED32;\t(* which of the values below the run carries *)\n')
    w('\tcategory: ARRAY nofValues OF SIGNED32;\n')
    w('\tupper, lower: ARRAY nofValues OF SIGNED32;\n')
    w('\tnruns, nvalues: SIGNED32;\n\n')
    w('PROCEDURE Hex(CONST s: ARRAY OF CHAR; VAR i: SIZE; digits: SIGNED32): SIGNED32;\n')
    w('VAR v, k: SIGNED32; c: CHAR;\n')
    w('BEGIN\n')
    w('\tv := 0;\n')
    w('\tFOR k := 1 TO digits DO\n')
    w('\t\tc := s[i]; INC(i);\n')
    w('\t\tIF c <= "9" THEN v := v * 16 + (ORD(c) - ORD("0")) ELSE v := v * 16 + (ORD(c) - ORD("A") + 10) END\n')
    w('\tEND;\n')
    w('\tRETURN v\n')
    w('END Hex;\n\n')
    w('(* six hex digits of first code point, two of the value index *)\n')
    w('PROCEDURE R(CONST s: ARRAY OF CHAR);\n')
    w('VAR i: SIZE;\n')
    w('BEGIN\n')
    w('\ti := 0;\n')
    w('\tWHILE s[i] # 0X DO\n')
    w('\t\tstart[nruns] := Hex(s, i, 6); value[nruns] := Hex(s, i, 2); INC(nruns)\n')
    w('\tEND\n')
    w('END R;\n\n')
    w('(* two hex digits of category, then upper and lower delta, each biased by 800000H *)\n')
    w('PROCEDURE V(CONST s: ARRAY OF CHAR);\n')
    w('VAR i: SIZE;\n')
    w('BEGIN\n')
    w('\ti := 0;\n')
    w('\tWHILE s[i] # 0X DO\n')
    w('\t\tcategory[nvalues] := Hex(s, i, 2);\n')
    w('\t\tupper[nvalues] := Hex(s, i, 6) - 800000H;\n')
    w('\t\tlower[nvalues] := Hex(s, i, 6) - 800000H;\n')
    w('\t\tINC(nvalues)\n')
    w('\tEND\n')
    w('END V;\n\n')
    w('PROCEDURE Which(cp: SIGNED32): SIGNED32;\n')
    w('VAR lo, hi, mid: SIGNED32;\n')
    w('BEGIN\n')
    w('\tIF (cp < 0) OR (cp > MaxCode) THEN RETURN -1 END;\n')
    w('\tlo := 0; hi := nruns - 1;\n')
    w('\tWHILE lo < hi DO\n')
    w('\t\tmid := (lo + hi + 1) DIV 2;\n')
    w('\t\tIF start[mid] <= cp THEN lo := mid ELSE hi := mid - 1 END\n')
    w('\tEND;\n')
    w('\tRETURN value[lo]\n')
    w('END Which;\n\n')
    w('(** The general category of a code point; Cn for one Unicode does not assign. *)\n')
    w('PROCEDURE Category*(cp: SIGNED32): SIGNED32;\n')
    w('VAR i: SIGNED32;\n')
    w('BEGIN\n')
    w('\ti := Which(cp);\n')
    w('\tIF i < 0 THEN RETURN Cn END;\t(* outside the code space, not inside run zero *)\n')
    w('\tRETURN category[i]\n')
    w('END Category;\n\n')
    w('(** The simple upper case of cp, or cp when it has none. *)\n')
    w('PROCEDURE ToUpper*(cp: SIGNED32): SIGNED32;\n')
    w('BEGIN\n')
    w('\tIF (cp < 0) OR (cp > MaxCode) THEN RETURN cp END;\n')
    w('\tRETURN cp + upper[Which(cp)]\n')
    w('END ToUpper;\n\n')
    w('(** The simple lower case of cp, or cp when it has none. *)\n')
    w('PROCEDURE ToLower*(cp: SIGNED32): SIGNED32;\n')
    w('BEGIN\n')
    w('\tIF (cp < 0) OR (cp > MaxCode) THEN RETURN cp END;\n')
    w('\tRETURN cp + lower[Which(cp)]\n')
    w('END ToLower;\n\n')
    w('PROCEDURE IsUpper*(cp: SIGNED32): BOOLEAN;\n')
    w('BEGIN\n\tRETURN Category(cp) = Lu\nEND IsUpper;\n\n')
    w('PROCEDURE IsLower*(cp: SIGNED32): BOOLEAN;\n')
    w('BEGIN\n\tRETURN Category(cp) = Ll\nEND IsLower;\n\n')
    w('(** A letter is any of Lu Ll Lt Lm Lo, which is what "letter" means in the standard. *)\n')
    w('PROCEDURE IsLetter*(cp: SIGNED32): BOOLEAN;\n')
    w('VAR c: SIGNED32;\n')
    w('BEGIN\n\tc := Category(cp);\n\tRETURN (c >= Lu) & (c <= Lo)\nEND IsLetter;\n\n')
    w('(** A decimal digit: Nd, not the other numbers -- Roman numerals are Nl and one half is No. *)\n')
    w('PROCEDURE IsDigit*(cp: SIGNED32): BOOLEAN;\n')
    w('BEGIN\n\tRETURN Category(cp) = Nd\nEND IsDigit;\n\n')
    w('PROCEDURE IsNumber*(cp: SIGNED32): BOOLEAN;\n')
    w('VAR c: SIGNED32;\n')
    w('BEGIN\n\tc := Category(cp);\n\tRETURN (c >= Nd) & (c <= No)\nEND IsNumber;\n\n')
    w('PROCEDURE IsLetterOrDigit*(cp: SIGNED32): BOOLEAN;\n')
    w('BEGIN\n\tRETURN IsLetter(cp) OR IsDigit(cp)\nEND IsLetterOrDigit;\n\n')
    w('(** Space is Zs Zl Zp plus the ASCII controls every language calls white space. *)\n')
    w('PROCEDURE IsSpace*(cp: SIGNED32): BOOLEAN;\n')
    w('VAR c: SIGNED32;\n')
    w('BEGIN\n')
    w('\tIF (cp = 9) OR (cp = 10) OR (cp = 11) OR (cp = 12) OR (cp = 13) THEN RETURN TRUE END;\n')
    w('\tc := Category(cp);\n')
    w('\tRETURN (c >= Zs) & (c <= Zp)\n')
    w('END IsSpace;\n\n')
    w('PROCEDURE IsControl*(cp: SIGNED32): BOOLEAN;\n')
    w('BEGIN\n\tRETURN Category(cp) = Cc\nEND IsControl;\n\n')
    w('PROCEDURE IsPunctuation*(cp: SIGNED32): BOOLEAN;\n')
    w('VAR c: SIGNED32;\n')
    w('BEGIN\n\tc := Category(cp);\n\tRETURN (c >= Pc) & (c <= Po)\nEND IsPunctuation;\n\n')
    w('PROCEDURE Values;\nBEGIN\n')
    for i in range(0, len(values), 6):
        chunk = "".join("%02X%06X%06X" % (c, (u + 0x800000) & 0xFFFFFF, (l + 0x800000) & 0xFFFFFF)
                        for c, u, l in values[i:i + 6])
        w('\tV("%s");\n' % chunk)
    w('END Values;\n\n')
    w('PROCEDURE Table;\nBEGIN\n')
    for i in range(0, len(runs), PER_LINE):
        chunk = "".join("%06X%02X" % (cp, v) for cp, v in runs[i:i + PER_LINE])
        w('\tR("%s");\n' % chunk)
    w('END Table;\n\n')
    w('BEGIN\n')
    w('\tnruns := 0; nvalues := 0;\n')
    w('\tValues; Table;\n')
    w('\tASSERT(nruns = nofRuns); ASSERT(nvalues = nofValues)\n')
    w('END Unicode.\n')
    text = out.getvalue()

    if "--check" in sys.argv:
        have = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if have != text:
            sys.exit("source/Unicode.Mod is not what tests/gen-unicode.py produces -- regenerate it")
        print("Unicode.Mod: %d runs, %d values, as the generator says" % (len(runs), len(values)))
        return
    io.open(OUT, "w", encoding="utf-8").write(text)
    print("wrote source/Unicode.Mod: %d runs, %d values" % (len(runs), len(values)))

main()
