#!/usr/bin/env bash
#
# Which of source/ is ours and which came from ETH — written down instead of remembered.
#
# The directory split answers half the question: everything in sdk/ is ours, everything in source/
# is the system. It cannot answer the other half, because a file we wrote and a file we changed
# look the same from outside. This lists both, against a vanilla tree given on the command line:
#
#   NEW      -- a module that is in source/ and in no vanilla tree. Ours outright.
#   CHANGED  -- a module that exists in both and differs. Ours only in the diff, and every one of
#               these is a candidate for a patch upstream rather than a fork-only delta.
#
# The vanilla trees are not in this repository and are not pinned by it; pass their roots, or set
# A2_VANILLA to a colon-separated list. Without them the script says so and stops, rather than
# reporting an empty answer that reads like "nothing of ours".
#
# Usage: sdk/ours.sh [vanilla-root ...]     (default: $A2_VANILLA, else ~/Projects/A2/{oberon,aos})

set -eo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"

roots=("$@")
if [ ${#roots[@]} -eq 0 ]; then
	if [ -n "${A2_VANILLA:-}" ]; then
		IFS=':' read -r -a roots <<< "$A2_VANILLA"
	else
		roots=("$HOME/Projects/A2/oberon" "$HOME/Projects/A2/aos")
	fi
fi

found=0
for r in "${roots[@]}"; do [ -d "$r" ] && found=1; done
if [ "$found" = 0 ]; then
	echo "no vanilla tree found in: ${roots[*]}" >&2
	echo "pass the roots on the command line or set A2_VANILLA" >&2
	exit 2
fi

new=0; changed=0; same=0
newlist=""; changedlist=""

for f in "$root"/source/*.Mod; do
	b="$(basename "$f")"
	origin=""
	for r in "${roots[@]}"; do
		for candidate in "$r/source/$b" "$r/$b"; do
			[ -f "$candidate" ] && { origin="$candidate"; break 2; }
		done
	done
	if [ -z "$origin" ]; then
		new=$((new+1)); newlist="$newlist$b"$'\n'
	elif cmp -s "$f" "$origin"; then
		same=$((same+1))
	else
		changed=$((changed+1)); changedlist="$changedlist$b"$'\n'
	fi
done

{
	echo "# What in source/ is ours"
	echo
	echo "Generated by \`sdk/ours.sh\`; do not edit by hand. Vanilla reference: ${roots[*]}"
	echo
	echo "Everything under \`sdk/\` is ours by construction. This is about \`source/\`, where our work"
	echo "and ETH's sit in one directory and cannot be told apart by looking."
	echo
	echo "| | modules |"
	echo "| --- | ---: |"
	echo "| ours outright (in no vanilla tree) | $new |"
	echo "| vanilla, changed by us | $changed |"
	echo "| vanilla, untouched | $same |"
	echo
	echo "## Ours outright"
	echo
	printf '%s' "$newlist" | while read -r m; do [ -n "$m" ] && echo "- \`$m\`"; done
	echo
	echo "## Vanilla, changed by us"
	echo
	echo "Each of these is a patch waiting to be written, not a fork-only delta. Where one has"
	echo "already gone upstream, it is in \`a2oberon/.planning/upstream/\`."
	echo
	printf '%s' "$changedlist" | while read -r m; do [ -n "$m" ] && echo "- \`$m\`"; done
} > "$root/sdk/OURS.md"

echo "sdk/OURS.md: $new ours, $changed changed, $same untouched"
